"""JSON / EPAC renderer: IR -> an EPAC ``Definitions`` scaffold.

Layout written under ``<out>/json/``:

    Definitions/
      global-settings.jsonc                 (pacEnvironments + pacOwnerId)
      policySetDefinitions/<name>.json       (customer-prefixed, posture-applied policyset)
      policyAssignments/<name>.json          (bound assignment, real scopes)
      policyExemptions/<selector>/<name>.json
    README.md

Effects are already baked per-group in the IR's policyset copy, so assignments carry
no effect ``overrides``. Output is deterministic (stable order, trailing newline).
"""
from pathlib import Path

from epac_builder.writeutil import write_json, write_text

SCHEMA = "https://raw.githubusercontent.com/Azure/enterprise-azure-policy-as-code/main/Schemas"


def render(ir, out_root):
    root = Path(out_root) / "json"
    defs = root / "Definitions"
    _write_global_settings(ir, defs / "global-settings.jsonc")

    for init in ir["initiatives"]:
        write_json(defs / "policySetDefinitions" / f"{init['name']}.json", init["policyset"])

    for asg in ir["assignments"]:
        write_json(defs / "policyAssignments" / f"{asg['assignmentName']}.json", _assignment(ir, asg))

    for ex in ir["exemptions"]:
        write_json(
            defs / "policyExemptions" / ex["selector"] / f"{ex['name']}.json",
            _exemption(ex),
        )

    write_text(root / "README.md", _readme(ir))
    return root


def _write_global_settings(ir, path):
    envs = []
    for e in ir["environments"]:
        entry = {
            "pacSelector": e["selector"],
            "cloud": "AzureCloud",
            "tenantId": e["tenantId"],
            "deploymentRootScope": e["rootScope"],
        }
        if e.get("managedIdentityLocation"):
            entry["managedIdentityLocation"] = e["managedIdentityLocation"]
        if e.get("notScopes"):
            entry["globalNotScopes"] = e["notScopes"]
        envs.append(entry)
    write_json(path, {
        "$schema": f"{SCHEMA}/global-settings-schema.json",
        "pacOwnerId": ir["identity"]["pacOwnerId"],
        "pacEnvironments": envs,
    })


def _assignment(ir, asg):
    out = {
        "$schema": f"{SCHEMA}/policy-assignment-schema.json",
        "nodeName": asg["nodeName"],
        "assignment": {
            "name": asg["assignmentName"],
            "displayName": asg["displayName"],
            "description": asg["description"],
        },
        "policySetDefinitionName": asg["initiative"],
        "parameters": asg["boundParameters"],
        "scope": asg["scopes"],
        "notScopes": asg["notScopes"] or [],
    }
    if asg["managedIdentity"]["required"]:
        out["managedIdentityLocations"] = _mi_locations(ir, asg)
    return out


def _mi_locations(ir, asg):
    """EPAC managedIdentityLocations: {location: [scopes]} from each env's location."""
    by_loc = {}
    loc_of = {e["selector"]: e.get("managedIdentityLocation") for e in ir["environments"]}
    for selector, scopes in asg["scopes"].items():
        loc = loc_of.get(selector)
        if loc:
            by_loc.setdefault(loc, [])
            for s in scopes:
                if s not in by_loc[loc]:
                    by_loc[loc].append(s)
    return by_loc


def _exemption(ex):
    out = {
        "name": ex["name"],
        "displayName": ex.get("displayName", ex["name"]),
        "exemptionCategory": ex["category"],
        "scope": ex["scopes"][0] if len(ex["scopes"]) == 1 else ex["scopes"],
    }
    if ex.get("expiresOn"):
        out["expiresOn"] = ex["expiresOn"]
    if ex.get("policyDefinitionReferenceId"):
        out["policyDefinitionReferenceIds"] = [ex["policyDefinitionReferenceId"]]
    return out


def _readme(ir):
    lines = [
        f"# EPAC scaffold — {ir['identity']['customer']} (json flavour)",
        "",
        f"Catalogue version: `{ir['catalogueVersion']}`  ·  pacOwnerId: `{ir['identity']['pacOwnerId']}`",
        "",
        "Generated by the epac-builder (consumer). Deploy with EPAC; do not hand-edit —",
        "re-run the assembler from the manifest instead.",
        "",
        "## Initiatives",
        "",
        "| Initiative | Remediation | Effect posture |",
        "| --- | --- | --- |",
    ]
    posture_of = {a["initiative"]: a["effectPosture"] for a in ir["assignments"]}
    for init in ir["initiatives"]:
        rem = "yes" if init["hasRemediation"] else "no"
        lines.append(f"| {init['name']} | {rem} | {posture_of.get(init['name'], '')} |")
    lines.append("")
    return "\n".join(lines)
