// Generated by the epac-builder (consumer). Do not hand-edit.
targetScope = 'managementGroup'

@description('Location for system-assigned identities (remediation).')
param location string = deployment().location

resource pd_apim_tls 'Microsoft.Authorization/policyDefinitions@2021-06-01' = {
  name: 'apim-tls'
  properties: loadJsonContent('policies/apim-tls.definition.json')
}

resource ps_contoso_integration_esn_apim 'Microsoft.Authorization/policySetDefinitions@2021-06-01' = {
  name: 'contoso-integration-esn-apim'
  properties: union(loadJsonContent('policies/contoso-integration-esn-apim.policyset.json'), {
    policyDefinitions: [
      {
        policyDefinitionReferenceId: 'ee7495e7-3ba7-40b6-bfee-c29e22cc75d4'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/ee7495e7-3ba7-40b6-bfee-c29e22cc75d4'
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: 'c15dcc82-b93c-4dcb-9332-fbf121685b54'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/c15dcc82-b93c-4dcb-9332-fbf121685b54'
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '92bb331d-ac71-416a-8c91-02f2cb734ce4'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/92bb331d-ac71-416a-8c91-02f2cb734ce4'
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: 'd5448c98-e503-4fdd-bcd2-784960c00d04'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/d5448c98-e503-4fdd-bcd2-784960c00d04'
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: 'f1cc7827-022c-473e-836e-5a51cae0b249'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/f1cc7827-022c-473e-836e-5a51cae0b249'
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: 'ffe25541-3853-4f4e-b71d-064422294b11'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/ffe25541-3853-4f4e-b71d-064422294b11'
        parameters: {
          effect: {
            value: 'Audit'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '3aa03346-d8c5-4994-a5bc-7652c2a2aef1'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/3aa03346-d8c5-4994-a5bc-7652c2a2aef1'
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '1dc2fc00-2245-4143-99f4-874c937f13ef'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/1dc2fc00-2245-4143-99f4-874c937f13ef'
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '7ca8c8ac-3a6e-493d-99ba-c5fa35347ff2'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/7ca8c8ac-3a6e-493d-99ba-c5fa35347ff2'
        parameters: {
          effect: {
            value: 'DeployIfNotExists'
          }
          endpointType: {
            value: 'Management'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '1b0d74ac-4b43-4c39-a15f-594385adc38d'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/1b0d74ac-4b43-4c39-a15f-594385adc38d'
        parameters: {
          effect: {
            value: 'Modify'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: 'apim-tls'
        policyDefinitionId: pd_apim_tls.id
        parameters: {
          effect: {
            value: 'Deny'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
    ]
  })
}

resource ps_contoso_management_esn_tags 'Microsoft.Authorization/policySetDefinitions@2021-06-01' = {
  name: 'contoso-management-esn-tags'
  properties: union(loadJsonContent('policies/contoso-management-esn-tags.policyset.json'), {
    policyDefinitions: [
      {
        policyDefinitionReferenceId: '8ce3da23-7156-49e4-b145-24f95f9dcb46'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/8ce3da23-7156-49e4-b145-24f95f9dcb46'
        parameters: {
          tagName: {
            value: '[parameters(\'requireTagValueResourceGroupsTagName\')]'
          }
          tagValue: {
            value: '[parameters(\'requireTagValueResourceGroupsTagValue\')]'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '1e30110a-5ceb-460c-a204-c1c3969c6d62'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62'
        parameters: {
          tagName: {
            value: '[parameters(\'requireTagValueResourcesTagName\')]'
          }
          tagValue: {
            value: '[parameters(\'requireTagValueResourcesTagValue\')]'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '96670d01-0a4d-4649-9c89-2d3abc0a5025'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/96670d01-0a4d-4649-9c89-2d3abc0a5025'
        parameters: {
          tagName: {
            value: '[parameters(\'requireTagResourceGroupsTagName\')]'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
      {
        policyDefinitionReferenceId: '871b6d14-10aa-478d-b590-94f262ecfa99'
        policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/871b6d14-10aa-478d-b590-94f262ecfa99'
        parameters: {
          tagName: {
            value: '[parameters(\'requireTagResourcesTagName\')]'
          }
        }
        groupNames: [
          'Essential'
        ]
      }
    ]
  })
}

resource asg_contoso_integration_esn_apim 'Microsoft.Authorization/policyAssignments@2022-06-01' = {
  name: 'integration-esn-apim'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    policyDefinitionId: ps_contoso_integration_esn_apim.id
    displayName: 'Integration Essential — API Management'
    notScopes: [ '/providers/Microsoft.Management/managementGroups/contoso-sandbox' ]
  }
}

resource asg_contoso_management_esn_tags 'Microsoft.Authorization/policyAssignments@2022-06-01' = {
  name: 'management-esn-tags'
  properties: {
    policyDefinitionId: ps_contoso_management_esn_tags.id
    displayName: 'Management Essential — Tags'
    parameters: loadJsonContent('policies/contoso-management-esn-tags.params.json')
    notScopes: [ '/providers/Microsoft.Management/managementGroups/contoso-sandbox' ]
  }
}

resource ra_contoso_integration_esn_apim_0 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(managementGroup().id, 'contoso-integration-esn-apim', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
  properties: {
    roleDefinitionId: '/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c'
    principalId: asg_contoso_integration_esn_apim.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource ra_contoso_integration_esn_apim_1 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(managementGroup().id, 'contoso-integration-esn-apim', '312a565d-c81f-4fd8-895a-4e21e48d571c')
  properties: {
    roleDefinitionId: '/providers/microsoft.authorization/roleDefinitions/312a565d-c81f-4fd8-895a-4e21e48d571c'
    principalId: asg_contoso_integration_esn_apim.identity.principalId
    principalType: 'ServicePrincipal'
  }
}
