#!/usr/bin/env python3
"""Per-version catalogue CHANGELOG, attributed by driver (#27, 27d).

Turns the machine diff (``catalogue_diff.diff_catalogues``) into a durable,
customer-readable Markdown entry that says *what changed and why* — classifying the
delta by the driver a customer engineer reasons about:

    upstream policies   Microsoft added/removed/changed built-ins (the recurring fetch)
    taxonomy/curation   we re-tiered / re-categorised groups (an ad-hoc hierarchy edit)
    engine              a renderer/generator change altered output shape

Run at each catalogue release to prepend an entry to ``catalogue/CHANGELOG.md``:

    # first release (no prior catalogue) — a baseline entry:
    python engine/tools/catalogue_changelog.py --write

    # subsequent releases — diff the previous catalogue against the current one:
    python engine/tools/catalogue_changelog.py --old <path/to/previous/catalogue> --write

The previous catalogue for a diff is any earlier catalogue tree — e.g. a git worktree
of the last release tag, or a copy kept aside. Without ``--write`` the entry is printed.
Stdlib only. Feeds #15 (per-customer package-upgrade impact).
"""
import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # engine/ root
from shared.changelog import released_versions, version_collision  # noqa: E402
from tools.catalogue_diff import (  # noqa: E402
    UnreadableCatalogue, diff_catalogues, find_provenance, scan)

try:
    sys.stdout.reconfigure(encoding="utf-8")
except AttributeError:
    pass

DEFAULT_CATALOGUE = Path(__file__).resolve().parents[2] / "catalogue"
TITLE = "# Catalogue changelog"
INTRO = ("Per-version record of what changed in the shared catalogue and **why**, attributed to "
         "its driver — upstream Microsoft policy changes, taxonomy/classification (curation), or "
         "engine changes. Newest first. Generated by `engine/tools/catalogue_changelog.py`.")


def _meta(root):
    prov, _ = find_provenance(Path(root))
    prov = prov or {}
    return {
        "version": prov.get("catalogueVersion", "?"),
        "date": (prov.get("generatedAt", "") or datetime.now(timezone.utc).isoformat())[:10],
        "engine": prov.get("producedByEngine"),
        "contentHash": prov.get("contentHash"),
        "builtInsRef": (prov.get("inputs", {}) or {}).get("builtInsRef"),
        "counts": prov.get("counts", {}),
    }


def _stamp_line(m):
    bits = [f"Engine `{m['engine']}`"] if m["engine"] else []
    if m["contentHash"]:
        bits.append(f"contentHash `{m['contentHash']}`")
    if m["builtInsRef"]:
        bits.append(f"builtInsRef `{m['builtInsRef']}`")
    return "_" + " · ".join(bits) + "_" if bits else ""


def _examples(rows, label, limit=8):
    if not rows:
        return []
    out = [f"- **{label}** ({len(rows)}):"]
    for r in rows[:limit]:
        grp = "/".join(x for x in r.get("group", ()) if x) if isinstance(r.get("group"), (list, tuple)) else ""
        detail = r.get("move") or grp
        name = (r.get("name") or "")[:60]
        out.append(f"  - `{r['guid']}` {detail}  {name}".rstrip())
    if len(rows) > limit:
        out.append(f"  - …and {len(rows) - limit} more")
    return out


def baseline_entry(new_root):
    m = _meta(new_root)
    idx, n_sets, failures = scan(Path(new_root))
    if failures:
        # Same rule as diff_entry: a baseline that silently under-counts becomes the
        # reference every later entry is measured against (#46).
        raise UnreadableCatalogue(Path(new_root).resolve(), failures, n_sets)
    n_pol = len(idx)
    lines = [f"## {m['version']} — {m['date']}", "", _stamp_line(m), "",
             f"Baseline catalogue. {len(m['counts']) and m['counts'].get('groups', n_sets)} groups, "
             f"{n_pol} policies across {n_sets} initiatives."]
    return "\n".join(l for l in lines if l is not None).strip() + "\n"


def diff_entry(old_root, new_root):
    rep = diff_catalogues(old_root, new_root)
    m = _meta(new_root)
    c = rep["counts"]
    attr = rep["attribution"]
    lines = [f"## {m['version']} — {m['date']}", "", _stamp_line(m), ""]
    lines.append("**Drivers:** " + ", ".join(attr.get("drivers") or ["—"]))
    lines += ["", "| Change | Count |", "|---|---|",
              f"| Policies added | {c['added']} |",
              f"| Policies removed | {c['removed']} |",
              f"| Re-tiered | {c['retiered']} |",
              f"| Re-categorised | {c['recategorised']} |",
              f"| Effect changed | {c['effectChanged']} |",
              f"| Unchanged | {c['unchanged']} |", ""]
    if attr.get("attributable") and attr.get("upstreamChanged"):
        lines.append(f"Upstream: `{attr.get('oldBuiltInsRef')}` → `{attr.get('newBuiltInsRef')}`.")
        lines.append("")
    body = (_examples(rep["added"], "Added") + _examples(rep["removed"], "Removed")
            + _examples(rep["retiered"], "Re-tiered") + _examples(rep["recategorised"], "Re-categorised")
            + _examples(rep["effectChanged"], "Effect changed"))
    lines += body or ["_No policy-level changes (provenance/version-only bump)._"]
    return "\n".join(lines).strip() + "\n"


def prepend(changelog_path, entry_md):
    p = Path(changelog_path)
    if not p.exists():
        p.write_text(f"{TITLE}\n\n{INTRO}\n\n{entry_md.strip()}\n", encoding="utf-8", newline="\n")
        return
    text = p.read_text(encoding="utf-8")
    idx = text.find("\n## ")
    if idx == -1:
        new = text.rstrip() + "\n\n" + entry_md.strip() + "\n"
    else:
        new = text[:idx].rstrip() + "\n\n" + entry_md.strip() + "\n" + text[idx:]
    p.write_text(new, encoding="utf-8", newline="\n")  # LF on every host (#52)


def main():
    ap = argparse.ArgumentParser(description="Per-version catalogue changelog (#27, 27d).")
    ap.add_argument("--new", default=str(DEFAULT_CATALOGUE), help="Current catalogue root (default: catalogue/)")
    ap.add_argument("--old", help="Previous catalogue root to diff against (omit for a baseline entry)")
    ap.add_argument("--changelog", default=str(DEFAULT_CATALOGUE / "CHANGELOG.md"),
                    help="CHANGELOG.md to prepend to (default: catalogue/CHANGELOG.md)")
    ap.add_argument("--write", action="store_true", help="Prepend the entry (else print to stdout)")
    args = ap.parse_args()

    # No --allow-unreadable escape hatch here, deliberately (#46): catalogue_diff.py can be
    # told to inspect a damaged tree because its output is a console report you are reading,
    # but a CHANGELOG entry is a durable claim about what changed. A wrong one is worse than
    # a missing one — it is indistinguishable from a real record once committed.
    try:
        entry = diff_entry(args.old, args.new) if args.old else baseline_entry(args.new)
    except UnreadableCatalogue as exc:
        print(f"ERROR: {exc}\nNo changelog entry written.", file=sys.stderr)
        return 2

    if args.write:
        # Second half of the #48 guard. apply_overlays refuses to *stamp* a colliding label;
        # this refuses to *record* one, so the ledger stays single-valued even if the stamp
        # was forced through with --allow-version-reuse or written by an older engine.
        m = _meta(args.new)
        clash = version_collision(m["version"], m["contentHash"], args.changelog)
        if clash:
            print(f"ERROR: {clash}\nNo changelog entry written.", file=sys.stderr)
            return 2
        if released_versions(args.changelog).get(m["version"]) == m["contentHash"]:
            # Same label, same content: this release is already recorded. Appending again
            # would put two identical entries in the ledger, which reads as two releases.
            print(f"[changelog] {m['version']} is already recorded with this contentHash — "
                  f"nothing to do.")
            return 0
        prepend(args.changelog, entry)
        print(f"[changelog] entry for {m['version']} -> {args.changelog}")
    else:
        print(entry)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
