variables:
  # This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
  PAC_OUTPUT_FOLDER: EPAC
  PAC_DEFINITIONS_FOLDER: EPAC/Definitions

pool:
  name: AzCoreACAPool

stages:
  - stage: Plan_Sandbox
    displayName: "Plan Sandbox mg-lv2-s"
    jobs:
      - job: Plan
        steps:
          - template: templates/buildDeploymentPlan.yml
            parameters:
              serviceConnection: sc-mg-lv2-s
              pacEnvironmentSelector: ps-mg-lv2-s

  - stage: Plan_NonProd
    displayName: "Plan NonProd Azure Policies mg-lv2-n"
    jobs:
      - job: Plan
        steps:
          - template: templates/buildDeploymentPlan.yml
            parameters:
              serviceConnection: sc-mg-lv2-n
              pacEnvironmentSelector: ps-mg-lv2-n

  - stage: Plan_Prod
    displayName: "Plan Prod Azure Policies mg-lv2-p"
    jobs:
      - job: Plan
        steps:
          - template: templates/buildDeploymentPlan.yml
            parameters:
              serviceConnection: sc-mg-lv2-p
              pacEnvironmentSelector: ps-mg-lv2-p
