# Generated by the epac-builder (consumer). Do not hand-edit.
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
  tenant_id = var.tenant_id
}

resource "azurerm_policy_set_definition" "contoso-integration-essential-api-management" {
  name                = "contoso-integration-essential-api-management"
  policy_type         = "Custom"
  display_name        = "Company Integration Essential — API Management"
  management_group_id = var.management_group_id

  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/ee7495e7-3ba7-40b6-bfee-c29e22cc75d4"
    reference_id         = "ee7495e7-3ba7-40b6-bfee-c29e22cc75d4"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Deny"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/c15dcc82-b93c-4dcb-9332-fbf121685b54"
    reference_id         = "c15dcc82-b93c-4dcb-9332-fbf121685b54"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Deny"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/92bb331d-ac71-416a-8c91-02f2cb734ce4"
    reference_id         = "92bb331d-ac71-416a-8c91-02f2cb734ce4"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Deny"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/d5448c98-e503-4fdd-bcd2-784960c00d04"
    reference_id         = "d5448c98-e503-4fdd-bcd2-784960c00d04"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Deny"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/f1cc7827-022c-473e-836e-5a51cae0b249"
    reference_id         = "f1cc7827-022c-473e-836e-5a51cae0b249"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Deny"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/ffe25541-3853-4f4e-b71d-064422294b11"
    reference_id         = "ffe25541-3853-4f4e-b71d-064422294b11"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Audit"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/3aa03346-d8c5-4994-a5bc-7652c2a2aef1"
    reference_id         = "3aa03346-d8c5-4994-a5bc-7652c2a2aef1"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Deny"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/1dc2fc00-2245-4143-99f4-874c937f13ef"
    reference_id         = "1dc2fc00-2245-4143-99f4-874c937f13ef"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Deny"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/7ca8c8ac-3a6e-493d-99ba-c5fa35347ff2"
    reference_id         = "7ca8c8ac-3a6e-493d-99ba-c5fa35347ff2"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "DeployIfNotExists"
      }
      "endpointType" = {
        "value" = "Management"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/1b0d74ac-4b43-4c39-a15f-594385adc38d"
    reference_id         = "1b0d74ac-4b43-4c39-a15f-594385adc38d"
    parameter_values     = jsonencode({
      "effect" = {
        "value" = "Modify"
      }
    })
    policy_group_names   = ["Essential"]
  }
}

resource "azurerm_policy_set_definition" "contoso-management-essential-tags" {
  name                = "contoso-management-essential-tags"
  policy_type         = "Custom"
  display_name        = "Company Management Essential — Tags"
  management_group_id = var.management_group_id

  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/8ce3da23-7156-49e4-b145-24f95f9dcb46"
    reference_id         = "8ce3da23-7156-49e4-b145-24f95f9dcb46"
    parameter_values     = jsonencode({
      "tagName" = {
        "value" = "[parameters('requireTagValueResourceGroupsTagName')]"
      }
      "tagValue" = {
        "value" = "[parameters('requireTagValueResourceGroupsTagValue')]"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62"
    reference_id         = "1e30110a-5ceb-460c-a204-c1c3969c6d62"
    parameter_values     = jsonencode({
      "tagName" = {
        "value" = "[parameters('requireTagValueResourcesTagName')]"
      }
      "tagValue" = {
        "value" = "[parameters('requireTagValueResourcesTagValue')]"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/96670d01-0a4d-4649-9c89-2d3abc0a5025"
    reference_id         = "96670d01-0a4d-4649-9c89-2d3abc0a5025"
    parameter_values     = jsonencode({
      "tagName" = {
        "value" = "[parameters('requireTagResourceGroupsTagName')]"
      }
    })
    policy_group_names   = ["Essential"]
  }
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/871b6d14-10aa-478d-b590-94f262ecfa99"
    reference_id         = "871b6d14-10aa-478d-b590-94f262ecfa99"
    parameter_values     = jsonencode({
      "tagName" = {
        "value" = "[parameters('requireTagResourcesTagName')]"
      }
    })
    policy_group_names   = ["Essential"]
  }
}

resource "azurerm_management_group_policy_assignment" "contoso-integration-essential-api-management" {
  name                 = "contoso-integration-esse"
  management_group_id  = var.management_group_id
  policy_definition_id = azurerm_policy_set_definition.contoso-integration-essential-api-management.id
  display_name         = "Company Integration Essential — API Management"
  not_scopes           = ["/providers/Microsoft.Management/managementGroups/contoso-sandbox"]
  location             = var.managed_identity_location
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_management_group_policy_assignment" "contoso-management-essential-tags" {
  name                 = "contoso-management-essen"
  management_group_id  = var.management_group_id
  policy_definition_id = azurerm_policy_set_definition.contoso-management-essential-tags.id
  display_name         = "Company Management Essential — Tags"
  parameters           = jsonencode({
    "requireTagValueResourceGroupsTagName" = {
      "value" = "environment"
    }
    "requireTagValueResourceGroupsTagValue" = {
      "value" = "production"
    }
    "requireTagValueResourcesTagName" = {
      "value" = "environment"
    }
    "requireTagValueResourcesTagValue" = {
      "value" = "production"
    }
    "requireTagResourceGroupsTagName" = {
      "value" = "costCenter"
    }
    "requireTagResourcesTagName" = {
      "value" = "costCenter"
    }
  })
  not_scopes           = ["/providers/Microsoft.Management/managementGroups/contoso-sandbox"]
}

resource "azurerm_role_assignment" "contoso-integration-essential-api-management_0" {
  scope              = var.management_group_id
  role_definition_id = "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
  principal_id       = azurerm_management_group_policy_assignment.contoso-integration-essential-api-management.identity[0].principal_id
}

resource "azurerm_role_assignment" "contoso-integration-essential-api-management_1" {
  scope              = var.management_group_id
  role_definition_id = "/providers/microsoft.authorization/roleDefinitions/312a565d-c81f-4fd8-895a-4e21e48d571c"
  principal_id       = azurerm_management_group_policy_assignment.contoso-integration-essential-api-management.identity[0].principal_id
}
